source 'https://rubygems.org'

gem 'cucumber'
gem 'capybara'
gem 'rspec'
gem 'rake'
gem 'selenium-webdriver'
gem 'pry'
gem 'kaminari'
gem 'brazilian-rails'
gem 'clipboard'
gem 'saucelabs'
gem 'rubyXL'
gem 'site_prism'
gem 'chromedriver-helper'
gem 'rails'